// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $personaje from "./routes/personaje.tsx";
import * as $Personaje from "./islands/Personaje.tsx";
import * as $PersonajesC from "./islands/PersonajesC.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/personaje.tsx": $personaje,
  },
  islands: {
    "./islands/Personaje.tsx": $Personaje,
    "./islands/PersonajesC.tsx": $PersonajesC,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
